### ISSUE TITLE
No wkhtmltopdf executable found

### ISSUE THREAD

**Issue by giacomopiva** [pdfkit/pdfkit#123]
I'm using rails 3.0.9 and ruby 1.8.7 and I'm getting this error:

No wkhtmltopdf executable found at 

> > Please install wkhtmltopdf - https://github.com/jdpace/PDFKit/wiki/Installing-WKHTMLTOPDF

The executable is installed and accessible (in the PATH) and it have 755 permissions.

**Comment by mcljot** [comment]
Hi folks, sorry to resurrect an old thread. I have the same issue that Blakey had, but which file do I paste the PDFKit.configure do stuff into?

Cheers!

**Comment by vcabana** [comment]
Just read this @mcljot. Is this resolved? Thanks.

**Comment by mcljot** [comment]
Hey, more or less resolved – through another method! Thanks!

**Comment by vcabana** [comment]
Great to hear @mcljot! :+1:

**Comment by jarthod** [comment]
Hi, A couple years latter I'm having a similar issue with this line again:
```
PDFKit::NoExecutableError (No wkhtmltopdf executable found at )
```

I'm using `wkhtmltopdf-binay` gem which in my setup provides the gem in:
```bash
> `which wkhtmltopdf`
=> "/home/deploy/.rbenv/versions/2.6.4/bin/wkhtmltopdf\n"
```

But from by Rails console if I do the `bundle exec which wkhtmltopdf` I get a tons of warning and an error message from bundler, the command doesn't work, returns empty string, and PDFKit fails with the (wrong) error message shown above:
```ruby
> `bundle exec which wkhtmltopdf`
/home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:105: warning: already initialized constant Bundler::FileUtils::VERSION
/home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/fileutils/lib/fileutils/version.rb:4: warning: previous definition of VERSION was here
/home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1284: warning: already initialized constant Bundler::FileUtils::Entry_::S_IF_DOOR
/home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/fileutils/lib/fileutils.rb:1267: warning: previous definition of S_IF_DOOR was here
/home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1568: warning: already initialized constant Bundler::FileUtils::Entry_::DIRECTORY_TERM
/home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/fileutils/lib/fileutils.rb:1547: warning: previous definition of DIRECTORY_TERM was here
/home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1626: warning: already initialized constant Bundler::FileUtils::OPT_TABLE
/home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/fileutils/lib/fileutils.rb:1602: warning: previous definition of OPT_TABLE was here
/home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1685: warning: already initialized constant Bundler::FileUtils::LOW_METHODS
/home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/fileutils/lib/fileutils.rb:1656: warning: previous definition of LOW_METHODS was here
/home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/vendor/fileutils/lib/fileutils.rb:1692: warning: already initialized constant Bundler::FileUtils::METHODS
/home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/fileutils/lib/fileutils.rb:1663: warning: previous definition of METHODS was here
Traceback (most recent call last):
	9: from /home/deploy/.rbenv/versions/2.6.4/bin/bundle:23:in `<main>'
	8: from /home/deploy/.rbenv/versions/2.6.4/bin/bundle:23:in `load'
	7: from /home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:13:in `<top (required)>'
	6: from /home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:13:in `require_relative'
	5: from /home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:7:in `<top (required)>'
	4: from /home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:7:in `require_relative'
	3: from /home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/errors.rb:3:in `<top (required)>'
	2: from /home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/errors.rb:20:in `<module:Bundler>'
	1: from /home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/errors.rb:20:in `<class:GemfileError>'
/home/deploy/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/errors.rb:9:in `status_code': Trying to register Bundler::GemfileError for status code 4 but Bundler::GemfileError is already registered (ArgumentError)
=> ""
```
I'm using bundler `v2.0.2`.

I see I'm not the first to have the problem and everyone is circumventing the problem with hack and hardcoding the path (eg https://stackoverflow.com/questions/32429977/why-cant-bundler-find-wkhtmltopdf-on-server?rq=1). Isn't it time we fix this?

In my case it seems it was running bundle exec from an ENV already started using bundler (`rails c`) was causing the problem, and updating rubygems + bundler fixed the problem for me: https://github.com/rubygems/bundler/issues/7484

But PDFKit still provides the wrong error message which doesn't help, also if `which wkhtmltopdf` works why not use this as a fallback? (or as first option) instead of raising an error?

Something like:
```ruby
def default_wkhtmltopdf
  return @default_command_path if @default_command_path
  if defined?(Bundler::GemfileError) && File.exists?('Gemfile')
    @default_command_path = `bundle exec which wkhtmltopdf`.chomp
  end
  @default_command_path = `which wkhtmltopdf` if @default_command_path&.empty?
end
```

What do you think?

**Comment by serene** [comment]
@jarthod Thanks for this suggestion. Can you make a PR with this change?

**Comment by jarthod** [comment]
@serene sure, here you go: #460
