### ISSUE TITLE
Windows RSPEC failures

### ISSUE THREAD

**Issue by cdwort** [pdfkit/pdfkit#318]
```
...............FFFFFF.F.F.F.F.F.F.F.FFFF.F.................F.....................FF.................FFFFF.FFF*FFFF.............

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) PDFKit#to_pdf should not throw an error if it is unable to connect
     # this test works for wkhtmltopdf-binary (0.9.9.1)
     Failure/Error: pdf = pdfkit.to_pdf
     Errno::ENOENT:
       No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --disable-smart-shrinking --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 http://localhost/this-should-not-be-found/404.html -
     # ./lib/pdfkit/pdfkit.rb:71:in `popen'
     # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
     # ./spec/pdfkit_spec.rb:475:in `block (3 levels) in <top (required)>'

Failures:

  1) PDFKit::Middleware should not get stuck rendering each request as pdf
     Failure/Error: get 'http://www.example.org/public/file.pdf'
     Errno::ENOENT:
       No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
     # ./lib/pdfkit/pdfkit.rb:71:in `popen'
     # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
     # ./lib/pdfkit/middleware.rb:21:in `call'
     # ./spec/middleware_spec.rb:395:in `block (2 levels) in <top (required)>'

  2) PDFKit::Middleware#call caching by default deletes ETag
     Failure/Error: get 'http://www.example.org/public/test.pdf'
     Errno::ENOENT:
       No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
     # ./lib/pdfkit/pdfkit.rb:71:in `popen'
     # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
     # ./lib/pdfkit/middleware.rb:21:in `call'
     # ./spec/middleware_spec.rb:41:in `block (5 levels) in <top (required)>'

  3) PDFKit::Middleware#call caching by default deletes Cache-Control
     Failure/Error: get 'http://www.example.org/public/test.pdf'
     Errno::ENOENT:
       No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
     # ./lib/pdfkit/pdfkit.rb:71:in `popen'
     # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
     # ./lib/pdfkit/middleware.rb:21:in `call'
     # ./spec/middleware_spec.rb:45:in `block (5 levels) in <top (required)>'

  4) PDFKit::Middleware#call caching when on preserves ETag
     Failure/Error: get 'http://www.example.org/public/test.pdf'
     Errno::ENOENT:
       No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
     # ./lib/pdfkit/pdfkit.rb:71:in `popen'
     # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
     # ./lib/pdfkit/middleware.rb:21:in `call'
     # ./spec/middleware_spec.rb:54:in `block (5 levels) in <top (required)>'

  5) PDFKit::Middleware#call caching when on preserves Cache-Control
     Failure/Error: get 'http://www.example.org/public/test.pdf'
     Errno::ENOENT:
       No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
     # ./lib/pdfkit/pdfkit.rb:71:in `popen'
     # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
     # ./lib/pdfkit/middleware.rb:21:in `call'
     # ./spec/middleware_spec.rb:59:in `block (5 levels) in <top (required)>'

  6) PDFKit::Middleware#call conditions :only regex one matching 
     Failure/Error: get 'http://www.example.org/public/test.pdf'
     Errno::ENOENT:
       No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
     # ./lib/pdfkit/pdfkit.rb:71:in `popen'
     # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
     # ./lib/pdfkit/middleware.rb:21:in `call'
     # ./spec/middleware_spec.rb:74:in `block (8 levels) in <top (required)>'

  7) PDFKit::Middleware#call conditions :only regex multiple matching 
     Failure/Error: get 'http://www.example.org/public/test.pdf'
     Errno::ENOENT:
       No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
     # ./lib/pdfkit/pdfkit.rb:71:in `popen'
     # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
     # ./lib/pdfkit/middleware.rb:21:in `call'
     # ./spec/middleware_spec.rb:94:in `block (8 levels) in <top (required)>'

  8) PDFKit::Middleware#call conditions :only string one matching 
     Failure/Error: get 'http://www.example.org/public/test.pdf'
     Errno::ENOENT:
       No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
     # ./lib/pdfkit/pdfkit.rb:71:in `popen'
     # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
     # ./lib/pdfkit/middleware.rb:21:in `call'
     # ./spec/middleware_spec.rb:116:in `block (8 levels) in <top (required)>'

  9) PDFKit::Middleware#call conditions :only string multiple matching 
     Failure/Error: get 'http://www.example.org/public/test.pdf'
     Errno::ENOENT:
       No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
     # ./lib/pdfkit/pdfkit.rb:71:in `popen'
     # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
     # ./lib/pdfkit/middleware.rb:21:in `call'
     # ./spec/middleware_spec.rb:136:in `block (8 levels) in <top (required)>'

  10) PDFKit::Middleware#call conditions :except regex one matching 
      Failure/Error: get 'http://www.example.org/public/test.pdf'
      Errno::ENOENT:
        No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
      # ./lib/pdfkit/pdfkit.rb:71:in `popen'
      # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
      # ./lib/pdfkit/middleware.rb:21:in `call'
      # ./spec/middleware_spec.rb:162:in `block (8 levels) in <top (required)>'

  11) PDFKit::Middleware#call conditions :except regex multiple matching 
      Failure/Error: get 'http://www.example.org/public/test.pdf'
      Errno::ENOENT:
        No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
      # ./lib/pdfkit/pdfkit.rb:71:in `popen'
      # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
      # ./lib/pdfkit/middleware.rb:21:in `call'
      # ./spec/middleware_spec.rb:182:in `block (8 levels) in <top (required)>'

  12) PDFKit::Middleware#call conditions :except string one matching 
      Failure/Error: get 'http://www.example.org/public/test.pdf'
      Errno::ENOENT:
        No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
      # ./lib/pdfkit/pdfkit.rb:71:in `popen'
      # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
      # ./lib/pdfkit/middleware.rb:21:in `call'
      # ./spec/middleware_spec.rb:204:in `block (8 levels) in <top (required)>'

  13) PDFKit::Middleware#call conditions :except string multiple matching 
      Failure/Error: get 'http://www.example.org/public/test.pdf'
      Errno::ENOENT:
        No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
      # ./lib/pdfkit/pdfkit.rb:71:in `popen'
      # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
      # ./lib/pdfkit/middleware.rb:21:in `call'
      # ./spec/middleware_spec.rb:224:in `block (8 levels) in <top (required)>'

  14) PDFKit::Middleware#call conditions saving generated pdf to disk when header PDFKit-save-pdf is present should saved the .pdf to disk
      Failure/Error: get 'http://www.example.org/public/test_save.pdf'
      Errno::ENOENT:
        No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
      # ./lib/pdfkit/pdfkit.rb:71:in `popen'
      # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
      # ./lib/pdfkit/middleware.rb:21:in `call'
      # ./spec/middleware_spec.rb:253:in `block (6 levels) in <top (required)>'

  15) PDFKit::Middleware#call conditions saving generated pdf to disk when header PDFKit-save-pdf is present should not raise when target directory does not exist
      Failure/Error: expect {
        expected no Exception, got #<Errno::ENOENT: No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -> with backtrace:
          # ./lib/pdfkit/pdfkit.rb:71:in `popen'
          # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
          # ./lib/pdfkit/middleware.rb:21:in `call'
          # ./spec/middleware_spec.rb:261:in `block (7 levels) in <top (required)>'
          # ./spec/middleware_spec.rb:260:in `block (6 levels) in <top (required)>'
      # ./spec/middleware_spec.rb:260:in `block (6 levels) in <top (required)>'

  16) PDFKit::Middleware#call conditions saving generated pdf to disk when header PDFKit-save-pdf is not present should not saved the .pdf to disk
      Failure/Error: get 'http://www.example.org/public/test_save.pdf'
      Errno::ENOENT:
        No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
      # ./lib/pdfkit/pdfkit.rb:71:in `popen'
      # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
      # ./lib/pdfkit/middleware.rb:21:in `call'
      # ./spec/middleware_spec.rb:269:in `block (6 levels) in <top (required)>'

  17) PDFKit::Middleware#call remove .pdf from PATH_INFO and REQUEST_URI matching 
      Failure/Error: get 'http://www.example.org/public/file.pdf'
      Errno::ENOENT:
        No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
      # ./lib/pdfkit/pdfkit.rb:71:in `popen'
      # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
      # ./lib/pdfkit/middleware.rb:21:in `call'
      # ./spec/middleware_spec.rb:282:in `block (5 levels) in <top (required)>'

  18) PDFKit::Middleware#call remove .pdf from PATH_INFO and REQUEST_URI subdomain matching 
      Failure/Error: get 'http://example.org/sub/public/file.pdf'
      Errno::ENOENT:
        No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
      # ./lib/pdfkit/pdfkit.rb:71:in `popen'
      # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
      # ./lib/pdfkit/middleware.rb:21:in `call'
      # ./spec/middleware_spec.rb:310:in `block (5 levels) in <top (required)>'

  19) PDFKit initialization parses hash option values into an array
      Failure/Error: expect(pdfkit.options['--replace']).to eql ['value', 'something else']

        expected: ["value", "something else"]
             got: ["value", "'something else'"]

        (compared using eql?)
      # ./spec/pdfkit_spec.rb:70:in `block (3 levels) in <top (required)>'

  20) PDFKit#command should encapsulate string arguments in quotes
      Failure/Error: expect(pdfkit.command).to include "--header-center foo\\ \\[page\\]"
        expected "C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe --disable-smart-shrinking --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 --header-center 'foo [page]' - -" to include "--header-center foo\\ \\[page\\]"
      # ./spec/pdfkit_spec.rb:217:in `block (3 levels) in <top (required)>'

  21) PDFKit#command should sanitize string arguments
      Failure/Error: expect(pdfkit.command).to include "--header-center \\$\\(ls\\)"
        expected "C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe --disable-smart-shrinking --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 --header-center $^(ls^) - -" to include "--header-center \\$\\(ls\\)"
      # ./spec/pdfkit_spec.rb:222:in `block (3 levels) in <top (required)>'

  22) PDFKit#to_pdf should generate a PDF of the HTML
      Failure/Error: pdf = pdfkit.to_pdf
      Errno::ENOENT:
        No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --disable-smart-shrinking --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
      # ./lib/pdfkit/pdfkit.rb:71:in `popen'
      # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
      # ./spec/pdfkit_spec.rb:412:in `block (3 levels) in <top (required)>'

  23) PDFKit#to_pdf should generate a PDF with a numerical parameter
      Failure/Error: pdf = pdfkit.to_pdf
      Errno::ENOENT:
        No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --disable-smart-shrinking --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 --header-spacing 1 - -
      # ./lib/pdfkit/pdfkit.rb:71:in `popen'
      # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
      # ./spec/pdfkit_spec.rb:418:in `block (3 levels) in <top (required)>'

  24) PDFKit#to_pdf should generate a PDF with a symbol parameter
      Failure/Error: pdf = pdfkit.to_pdf
      Errno::ENOENT:
        No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --disable-smart-shrinking --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
      # ./lib/pdfkit/pdfkit.rb:71:in `popen'
      # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
      # ./spec/pdfkit_spec.rb:424:in `block (3 levels) in <top (required)>'

  25) PDFKit#to_pdf should have the stylesheet added to the head if it has one
      Failure/Error: pdfkit.to_pdf
      Errno::ENOENT:
        No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --disable-smart-shrinking --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
      # ./lib/pdfkit/pdfkit.rb:71:in `popen'
      # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
      # ./spec/pdfkit_spec.rb:432:in `block (3 levels) in <top (required)>'

  26) PDFKit#to_pdf should prepend style tags if the HTML doesn't have a head tag
      Failure/Error: pdfkit.to_pdf
      Errno::ENOENT:
        No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --disable-smart-shrinking --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
      # ./lib/pdfkit/pdfkit.rb:71:in `popen'
      # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
      # ./spec/pdfkit_spec.rb:440:in `block (3 levels) in <top (required)>'

  27) PDFKit#to_pdf should be able to deal with ActiveSupport::SafeBuffer
      Failure/Error: pdfkit.to_pdf
      Errno::ENOENT:
        No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --disable-smart-shrinking --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
      # ./lib/pdfkit/pdfkit.rb:71:in `popen'
      # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
      # ./spec/pdfkit_spec.rb:455:in `block (3 levels) in <top (required)>'

  28) PDFKit#to_pdf should escape \X in stylesheets
      Failure/Error: pdfkit.to_pdf
      Errno::ENOENT:
        No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --disable-smart-shrinking --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
      # ./lib/pdfkit/pdfkit.rb:71:in `popen'
      # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
      # ./spec/pdfkit_spec.rb:463:in `block (3 levels) in <top (required)>'

  29) PDFKit#to_pdf should throw an error if it is unable to connect
      Failure/Error: expect { pdfkit.to_pdf }.to raise_error /exitstatus=1/
        expected /exitstatus=1/, got #<Errno::ENOENT: No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --disable-smart-shrinking --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 http://google.com/this-should-not-be-found/404.html -> with backtrace:
          # ./lib/pdfkit/pdfkit.rb:71:in `popen'
          # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
          # ./spec/pdfkit_spec.rb:470:in `block (4 levels) in <top (required)>'
          # ./spec/pdfkit_spec.rb:470:in `block (3 levels) in <top (required)>'
      # ./spec/pdfkit_spec.rb:470:in `block (3 levels) in <top (required)>'

  30) PDFKit#to_pdf should generate PDF if there are missing assets
      Failure/Error: pdf = pdfkit.to_pdf
      Errno::ENOENT:
        No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --disable-smart-shrinking --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - -
      # ./lib/pdfkit/pdfkit.rb:71:in `popen'
      # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
      # ./spec/pdfkit_spec.rb:481:in `block (3 levels) in <top (required)>'

  31) PDFKit#to_file should create a file with the PDF as content
      Got 0 failures and 2 other errors:

      31.1) Failure/Error: file = pdfkit.to_file(@file_path)
            Errno::ENOENT:
              No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --disable-smart-shrinking --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 - c:/Users/Amy/pdfkit/spec/fixtures/test.pdf
            # ./lib/pdfkit/pdfkit.rb:71:in `popen'
            # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
            # ./lib/pdfkit/pdfkit.rb:84:in `to_file'
            # ./spec/pdfkit_spec.rb:498:in `block (3 levels) in <top (required)>'

      31.2) Failure/Error: File.delete(@file_path)
            Errno::ENOENT:
              No such file or directory @ unlink_internal - c:/Users/Amy/pdfkit/spec/fixtures/test.pdf
            # ./spec/pdfkit_spec.rb:493:in `delete'
            # ./spec/pdfkit_spec.rb:493:in `block (3 levels) in <top (required)>'

  32) PDFKit#to_file should not truncate data (in Ruby 1.8.6)
      Got 0 failures and 2 other errors:

      32.1) Failure/Error: pdf_data = pdfkit.to_pdf
            Errno::ENOENT:
              No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --disable-smart-shrinking --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 c:/Users/Amy/pdfkit/spec/fixtures/example.html -
            # ./lib/pdfkit/pdfkit.rb:71:in `popen'
            # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
            # ./spec/pdfkit_spec.rb:506:in `block (3 levels) in <top (required)>'

      32.2) Failure/Error: File.delete(@file_path)
            Errno::ENOENT:
              No such file or directory @ unlink_internal - c:/Users/Amy/pdfkit/spec/fixtures/test.pdf
            # ./spec/pdfkit_spec.rb:493:in `delete'
            # ./spec/pdfkit_spec.rb:493:in `block (3 levels) in <top (required)>'

  33) PDFKit security should not allow shell injection in options
      Failure/Error: pdfkit.to_pdf
      Errno::ENOENT:
        No such file or directory - C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --disable-smart-shrinking --quiet --page-size Letter --margin-top 0.75in --margin-right 0.75in --margin-bottom 0.75in --margin-left 0.75in --encoding UTF-8 --header-center 'a title"; touch c:/Users/Amy/pdfkit/spec/fixtures/security-oops #' - -
      # ./lib/pdfkit/pdfkit.rb:71:in `popen'
      # ./lib/pdfkit/pdfkit.rb:71:in `to_pdf'
      # ./spec/pdfkit_spec.rb:525:in `block (3 levels) in <top (required)>'

1 deprecation warning total

Finished in 0.9828 seconds (files took 1.53 seconds to load)
127 examples, 33 failures, 1 pending

Failed examples:

rspec ./spec/middleware_spec.rb:385 # PDFKit::Middleware should not get stuck rendering each request as pdf
rspec ./spec/middleware_spec.rb:40 # PDFKit::Middleware#call caching by default deletes ETag
rspec ./spec/middleware_spec.rb:44 # PDFKit::Middleware#call caching by default deletes Cache-Control
rspec ./spec/middleware_spec.rb:53 # PDFKit::Middleware#call caching when on preserves ETag
rspec ./spec/middleware_spec.rb:58 # PDFKit::Middleware#call caching when on preserves Cache-Control
rspec ./spec/middleware_spec.rb:73 # PDFKit::Middleware#call conditions :only regex one matching 
rspec ./spec/middleware_spec.rb:93 # PDFKit::Middleware#call conditions :only regex multiple matching 
rspec ./spec/middleware_spec.rb:115 # PDFKit::Middleware#call conditions :only string one matching 
rspec ./spec/middleware_spec.rb:135 # PDFKit::Middleware#call conditions :only string multiple matching 
rspec ./spec/middleware_spec.rb:161 # PDFKit::Middleware#call conditions :except regex one matching 
rspec ./spec/middleware_spec.rb:181 # PDFKit::Middleware#call conditions :except regex multiple matching 
rspec ./spec/middleware_spec.rb:203 # PDFKit::Middleware#call conditions :except string one matching 
rspec ./spec/middleware_spec.rb:223 # PDFKit::Middleware#call conditions :except string multiple matching 
rspec ./spec/middleware_spec.rb:250 # PDFKit::Middleware#call conditions saving generated pdf to disk when header PDFKit-save-pdf is present should saved the .pdf to disk
rspec ./spec/middleware_spec.rb:257 # PDFKit::Middleware#call conditions saving generated pdf to disk when header PDFKit-save-pdf is present should not raise when target directory does not exist
rspec ./spec/middleware_spec.rb:267 # PDFKit::Middleware#call conditions saving generated pdf to disk when header PDFKit-save-pdf is not present should not saved the .pdf to disk
rspec ./spec/middleware_spec.rb:281 # PDFKit::Middleware#call remove .pdf from PATH_INFO and REQUEST_URI matching 
rspec ./spec/middleware_spec.rb:309 # PDFKit::Middleware#call remove .pdf from PATH_INFO and REQUEST_URI subdomain matching 
rspec ./spec/pdfkit_spec.rb:68 # PDFKit initialization parses hash option values into an array
rspec ./spec/pdfkit_spec.rb:215 # PDFKit#command should encapsulate string arguments in quotes
rspec ./spec/pdfkit_spec.rb:220 # PDFKit#command should sanitize string arguments
rspec ./spec/pdfkit_spec.rb:410 # PDFKit#to_pdf should generate a PDF of the HTML
rspec ./spec/pdfkit_spec.rb:416 # PDFKit#to_pdf should generate a PDF with a numerical parameter
rspec ./spec/pdfkit_spec.rb:422 # PDFKit#to_pdf should generate a PDF with a symbol parameter
rspec ./spec/pdfkit_spec.rb:428 # PDFKit#to_pdf should have the stylesheet added to the head if it has one
rspec ./spec/pdfkit_spec.rb:436 # PDFKit#to_pdf should prepend style tags if the HTML doesn't have a head tag
rspec ./spec/pdfkit_spec.rb:451 # PDFKit#to_pdf should be able to deal with ActiveSupport::SafeBuffer
rspec ./spec/pdfkit_spec.rb:459 # PDFKit#to_pdf should escape \X in stylesheets
rspec ./spec/pdfkit_spec.rb:468 # PDFKit#to_pdf should throw an error if it is unable to connect
rspec ./spec/pdfkit_spec.rb:479 # PDFKit#to_pdf should generate PDF if there are missing assets
rspec ./spec/pdfkit_spec.rb:496 # PDFKit#to_file should create a file with the PDF as content
rspec ./spec/pdfkit_spec.rb:503 # PDFKit#to_file should not truncate data (in Ruby 1.8.6)
rspec ./spec/pdfkit_spec.rb:523 # PDFKit security should not allow shell injection in options

Coverage report generated for RSpec to c:/Users/Amy/pdfkit/coverage. 186 / 206 LOC (90.29%) covered.
```

**Comment by cdwort** [comment]
Looks like the `IO.popen` might be doing the wrong thing, or I've just messed up my setup.

**Comment by sigmavirus24** [comment]
Is this resolved?

**Comment by cdwort** [comment]
Nope, haven't gotten back to this. We still likely have a broken a broken test suite on windows.

**Comment by harmansingh2908** [comment]
i have an issue regarding pdfkit tool.I am creating a doc file using pdfkit on server.when file is download on windows or mac machine from server.Then it is shown in binary format.Same file is opened in ubuntu in text format.how can i resolve this problem..

**Comment by sigmavirus24** [comment]
@harmansingh2908 it sounds like you have the wrong project. Further, all questions belong on [StackOverflow](https://stackoverflow.com/) as issue trackers are not support forums.
