### ISSUE TITLE
Error when trying to embed woff2 font

### ISSUE THREAD

**Issue by codeandcats** [pdfkit/pdfkit#378]
In node, I've tried embedding a number of .woff2 fonts from Google Fonts but they all error with:

```
TypeError: Cannot read property 'length' of undefined                                                                                                                     
    at WOFF2Glyph._getContours (/node_modules/pdfkit/node_modules/fontkit/index.js:9464:33)                  
    at WOFF2Glyph._getPath (/node_modules/pdfkit/node_modules/fontkit/index.js:9499:27)                      
    at WOFF2Glyph.get (/node_modules/pdfkit/node_modules/fontkit/index.js:9067:19)                           
    at WOFF2Glyph.descriptor.get (/node_modules/pdfkit/node_modules/fontkit/index.js:92:21)                  
    at WOFF2Glyph._getCBox (/node_modules/pdfkit/node_modules/fontkit/index.js:11955:18)                     
    at WOFF2Glyph._getMetrics (/node_modules/pdfkit/node_modules/fontkit/index.js:9482:23)                   
    at WOFF2Glyph.get (/node_modules/pdfkit/node_modules/fontkit/index.js:9078:19)                           
    at WOFF2Glyph.descriptor.get (/node_modules/pdfkit/node_modules/fontkit/index.js:92:21)                  
    at new EmbeddedFont (/node_modules/pdfkit/js/font/embedded.js:23:43)                                     
    at Function.PDFFont.open (/node_modules/pdfkit/js/font.js:25:14) 
```

[This simple project](https://github.com/codeandcats/pdfkit-woff-bug) demonstrates the error.

Am I doing something wrong? All the .ttf files I've tried from Google Fonts appear to work fine.

**Comment by codeandcats** [comment]
Sorry, I just realised that I posted this issue in the wrong repo (I meant to post in the javascript implementation of PDFKit).
