### ISSUE TITLE
Having Issue running pdfkit on Raspbian

### ISSUE THREAD

**Issue by jeremylinlin** [pdfkit/pdfkit#401]
I've been working on this problem for hours and still can't get it solved. Things works totally fine on my Mac until I migrate my code to my raspberry pi.

```
/home/pi/.rvm/gems/ruby-2.4.0/gems/wkhtmltopdf-binary-0.12.3.1/bin/wkhtmltopdf_linux_x86: 1: /home/pi/.rvm/gems/ruby-2.4.0/gems/wkhtmltopdf-binary-0.12.3.1/bin/wkhtmltopdf_linux_x86: Syntax error: "(" unexpected
/home/pi/.rvm/gems/ruby-2.4.0/gems/pdfkit-0.8.2/lib/pdfkit/pdfkit.rb:190:in `size': No such file or directory @ rb_file_s_size - /home/pi/Projects/Scripts/html_to_pdf/out/test.pdf (Errno::ENOENT)
	from /home/pi/.rvm/gems/ruby-2.4.0/gems/pdfkit-0.8.2/lib/pdfkit/pdfkit.rb:190:in `empty_result?'
	from /home/pi/.rvm/gems/ruby-2.4.0/gems/pdfkit-0.8.2/lib/pdfkit/pdfkit.rb:71:in `to_pdf'
	from /home/pi/.rvm/gems/ruby-2.4.0/gems/pdfkit-0.8.2/lib/pdfkit/pdfkit.rb:76:in `to_file'
	from vbaike_html_to_pdf.rb:14:in `block in <main>'
	from vbaike_html_to_pdf.rb:12:in `each'
	from vbaike_html_to_pdf.rb:12:in `<main>'
```

**Comment by serene** [comment]
This is a problem with wkhtmltopdf compatibility and is not an issue with pdfkit.
