### ISSUE TITLE
cannot connect to X server Errno::EPIPE: Broken pipe

### ISSUE THREAD

**Issue by aruprakshit** [pdfkit/pdfkit#411]
I am getting an error in my Ubuntu OS. The error is:

```sh
pdf = printer.generate
The switch --footer-right, is not support using unpatched qt, and will be ignored.The switch --footer-font-size, is not support using unpatched qt, and will be ignored.The switch --footer-center, is not support using unpatched qt, and will be ignored.The switch --header-html, is not support using unpatched qt, and will be ignored.The switch --header-spacing, is not support using unpatched qt, and will be ignored.The switch --footer-spacing, is not support using unpatched qt, and will be ignored.wkhtmltopdf: cannot connect to X server
Errno::EPIPE: Broken pipe
	from /home/inspection/application/releases/158/backend/ruby/vendor/bundle/ruby/2.4.0/gems/pdfkit-0.8.2/lib/pdfkit/pdfkit.rb:64:in `write'
	from /home/inspection/application/releases/158/backend/ruby/vendor/bundle/ruby/2.4.0/gems/pdfkit-0.8.2/lib/pdfkit/pdfkit.rb:64:in `puts'
	from /home/inspection/application/releases/158/backend/ruby/vendor/bundle/ruby/2.4.0/gems/pdfkit-0.8.2/lib/pdfkit/pdfkit.rb:64:in `block in to_pdf'
	from /home/inspection/application/releases/158/backend/ruby/vendor/bundle/ruby/2.4.0/gems/pdfkit-0.8.2/lib/pdfkit/pdfkit.rb:63:in `popen'
	from /home/inspection/application/releases/158/backend/ruby/vendor/bundle/ruby/2.4.0/gems/pdfkit-0.8.2/lib/pdfkit/pdfkit.rb:63:in `to_pdf'
	from /home/inspection/application/releases/158/backend/ruby/vendor/bundle/ruby/2.4.0/gems/pdfkit-0.8.2/lib/pdfkit/pdfkit.rb:76:in `to_file'
	from /home/inspection/application/releases/158/backend/ruby/app/services/pdf_printer.rb:48:in `generate'
	from (irb):4
	from /home/inspection/application/releases/158/backend/ruby/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/commands/console.rb:110:in `start'
	from /home/inspection/application/releases/158/backend/ruby/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
	from /home/inspection/application/releases/158/backend/ruby/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/inspection/application/releases/158/backend/ruby/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/inspection/application/releases/158/backend/ruby/vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'
```

The version of wkhtmltopdf is as follows.

```sh
$ wkhtmltopdf -V
Name:
  wkhtmltopdf 0.12.0 final

License:
  Copyright (C) 2010 wkhtmltopdf/wkhtmltoimage Authors.



  License LGPLv3+: GNU Lesser General Public License version 3 or later
  <http://gnu.org/licenses/lgpl.html>. This is free software: you are free to
  change and redistribute it. There is NO WARRANTY, to the extent permitted by
  law.
```

I installed wkhtmltopdf as described [here](https://gist.github.com/brunogaspar/bd89079245923c04be6b0f92af431c10#file-readme-md).

Any idea how to fix this?

**Comment by heaven** [comment]
You need to als install xvfb and run it.

**Comment by heaven** [comment]
I am wondering why docs don't mentioned we need X server? It would also be great to be able to use `xvfb-run`.
