### ISSUE TITLE
Wkhtmltopdf 0.12.5 system install with capybara

### ISSUE THREAD

**Issue by map7** [pdfkit/pdfkit#421]
I've just installed wkhtmltopdf on my Debian 8 system, I'm using Rails 5.2.0 and Capybara 3.2.1. This setup was working with the wkhtmltopdf_binary-gem (0.12.3.1) in test and development mode. Now that I'm using the system install of wkhtmltopdf it works in development mode but not in my end-to-end Capybara tests. I get the following error;

Failure/Error: @kit.to_file(file_name)
     
     RuntimeError:
       command failed (exitstatus=1): /usr/local/bin/wkhtmltopdf --encoding UTF-8 --dpi 300 --margin-top 30 --margin-bottom 23 --margin-left 10 --margin-right 10 --header-spacing 0 --header-html /tmp/header20180709-23495-1112tq3.html --footer-spacing 2 --footer-html /tmp/footer20180709-23495-adadvl.html --quiet --user-style-sheet /home/map7/code/project/app/assets/stylesheets/pdfkit.scss - /tmp/invoice20180709-23495-1xv14ko.pdf
     # ./app/models/pdf_report.rb:102:in `save_pdf'
     # ./app/models/pdf_report.rb:21:in `initialize'
     # ./app/controllers/reports_controller.rb:65:in `new'
     # ./app/controllers/reports_controller.rb:65:in `block (2 levels) in trial_balance'
     # ./app/controllers/reports_controller.rb:43:in `trial_balance'
     # ./spec/support/no_animations.rb:12:in `call'
     # ------------------
     # --- Caused by: ---
     # Capybara::CapybaraError:
     #   Your application server raised an error - It has been raised in your test code because Capybara.raise_server_errors == true
     #   -e:1:in `<main>'

**Comment by serene** [comment]
Can you ensure that the wkhtmltopdf_binary gem is completely uninstalled?

**Comment by map7** [comment]
I've removed all wkhtmltopdf_binary gems off the server and still have the problem. But have done some investigating and found that it's the header and footer in the PDFKIT under test conditions which seems to be causing the error.

Below is my configuration which works in dev, staging and production but not in tests. If I take out the header_html and footer_html it works in the tests.

    PDFKit.configure do |config|
      config.wkhtmltopdf = "/usr/local/bin/wkhtmltopdf"

      config.default_options = {
        encoding:"UTF-8",
        dpi: '300',
        margin_top: '30',
        margin_bottom: '23',
        margin_left: '10',
        margin_right: '10',
        header_spacing: '0',
        header_html: render_header_footer("header"),
        footer_spacing: '2',
        footer_html: render_header_footer("footer"),
        quiet: true,
        :"user-style-sheet" => "#{Rails.root}/app/assets/stylesheets/pdfkit.scss"
      }
    end

What I think is happening is the header and footer html is getting rendered and removed before wkhtmltopdf gets a chance to finish.

**Comment by map7** [comment]
I found that if I remark out my file.rewind in the render method then it works;

```
# Render the footer out to a temp file
# PDFkit will only accept a file or URL, it will not accept raw text the way you expect.
# ie; passing the erb compiled output directly back to pdfkit results in non-dynamic content being displayed.
  def render_header_footer(type)
    compiled = ERB.new(File.read("#{Rails.root}/app/views/reports/#{type}.html.erb")).result(binding)
    file = Tempfile.new(["#{type}",".html"])
    file.write(compiled)
    #file.rewind
    file.path
  end
```

**Comment by map7** [comment]
Sorry to reopen this, but if I take the file.rewind out then I don't get a header or footer in test, dev, or production. file.close breaks tests also
