### ISSUE TITLE
PDF generation fails with exitstatus=134 intermittently

### ISSUE THREAD

**Issue by abhishek77in** [pdfkit/pdfkit#482]
Hi,

I am running into an issue where the PDF printing is failing intermittently (about 1% of the times) but works after the job is re-tried. I am trying to debug the issue but only thing I can see is `exitstatus=134` and I feel there is not much to go on from here.

I have verbose mode on, can I do anything else to get more insight in the issue? I have found one more issue with same exitstatus - https://github.com/barryvdh/laravel-snappy/issues/122 but not sure if my issue is the same.

**How do I debug this further?**

```
vendor/bundle/ruby/2.6.0/gems/pdfkit-0.8.4.1/lib/pdfkit/pdfkit.rb:73:in `to_pdf': command failed (exitstatus=134): /app/vendor/bundle/ruby/2.6.0/gems/wkhtmltopdf-heroku-2.12.5.0/bin/wkhtmltopdf-linux-amd64 --encoding UTF-8 --dpi 300 --header-spacing 3 --page-size A4 --margin-top 81.0 --margin-bottom 68.0 --margin-left 0 --margin-right 0 --header-html /app/tmp/LabReport-L1-BabyAmara\(1YRS-F\)-25-10-2020\ header20201025-4-1wb3iw7.html --footer-html /app/tmp/LabReport-L1-BabyAmara\(1YRS-F\)-25-10-2020\ footer20201025-4-w1oxfj.html - - (RuntimeError)
    from app/models/lab_report_pdf.rb:28:in `to_pdf'
    from app/models/lab_report.rb:46:in `save_as_pdf'
 ```

**Comment by abhishek77in** [comment]
The issue was due to tempfile getting garbage collected. More on this here - https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4861 and https://www.hilman.io/blog/2016/01/tempfile/
